### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by erayko-dev** [Nerfednijt/nxte-mrpdheist#1]
I wanted to know how the player could unlock the doors without having the police role? Thanks, amazing script though!

**Comment by Nerfednijt** [comment]
there are multiple ways to do this :
1 - You can make a new item that can open the doors 
2 - you can make it so that once the hack is complete it opens the doors 

if you want you can join my discord https://discord.gg/yGYWVdrpY5 and ill be able to help you there

**Comment by erayko-dev** [comment]
joined @Nerfednijt thanks for the fast response I appreciate the help
